#!/bin/bash

SCRIPT_FILE_NAME=$(basename $0)
SCRIPT_NAME=${SCRIPT_FILE_NAME%.*}
SELF=$(cd $(dirname $0); pwd)
VERSION="1.0.0"
LOGGING=false

function _usage() {
    echo "Usage: ${SCRIPT_NAME} [OPTIONS] [SEED_FILE]"
    echo "  This script is ~."
    echo
    echo "Options:"
    echo "  -h, --help                     Show help."
    echo "  -v, --version                  Show script version."
    echo "  -n, --length ARG               length of output chars."
    echo "  -n, --number ARG               number of output char lines."
    echo "      --no-symbol                No symbol within output."
    echo "      --verbose                  Print various logging information"
    echo
    exit 1
}

function _log() {
    ${LOGGING} && echo "$@" || return 0
}

function _err() {
    echo "[err] $1" && exit 1
}

function _args_count() {
    echo ${#ARG_VALUES[@]}
}

function _is_exist() {
    [ -f $1 ] || [ -d $1 ] || [[ $(type $1) ]]
}

function _verbose() {
    _log "SEED_DIR: ${SEED_DIR}"
    _log "OUT_CHAR_LENGTH: ${OUT_CHAR_LENGTH}"
    _log "OUT_LINE_NUMBER: ${OUT_LINE_NUMBER}"
    _log "NO_SYMBOL: ${NO_SYMBOL}"
}

SEED_DIR="${SELF}/seed"
OUT_CHAR_LENGTH=20
OUT_LINE_NUMBER=1
NO_SYMBOL='false'

function _main() {
    local format=${ARG_VALUES[0]}
    case ${format} in
        'han' | 'hankaku' )
            ${NO_SYMBOL} && {
                seed=($(cat ${SEED_DIR}/hankaku.txt \
                        | head -n 3 \
                        | sed -e 's/ //g' \
                        | fold -w1))
            } || {
                seed=($(cat ${SEED_DIR}/hankaku.txt \
                        | fold -w 1))
            }
            ;;
        'zen' | 'zenkaku')
            seed=($(fold -w 1 ${SEED_DIR}/zenkaku.txt))
            ;;
        *)
            [ ! -e ${ARG_VALUES[0]} ] && _err "No file of ${ARG_VALUES[0]}"
            seed=($(fold -w 1 ${SEED_DIR}/zenkaku.txt \
                                ${SEED_DIR}/hankaku.txt \
                                ${ARG_VALUES[0]}))
            ;;
    esac

    for n in $(seq ${OUT_LINE_NUMBER}); do
        for i in $(seq ${OUT_CHAR_LENGTH}); do
            char_line+=${seed[$((${RANDOM} % ${#seed[*]}))]}
        done
        echo ${char_line[@]}
        char_line=""
    done
}

# -------------------------------------------------------------
# Arguments and Options
# -------------------------------------------------------------

ARG_VALUES=()
SAMPLE_OPTION_A=""
SAMPLE_OPTION_B=""
SAMPLE_OPTION_FLAG_N=false
SAMPLE_OPTION_FLAG_L=false
SAMPLE_OPTION_FLAG_P=false

function _analyse_args_and_options() {
    while (( $# > 0 ))
    do
        case $1 in
            -h | --help)
                _usage
                exit 1
                ;;
            -v | --version)
                echo ${VERSION}
                exit 1
                ;;
            --verbose)
                LOGGING=true
                shift
                ;;
            -l | --length)                  # Must have argument
                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    _err "-l option requires a value."
                fi
                OUT_CHAR_LENGTH=$2
                shift 2
                ;;
            -n | --number)                  # Must have argument
                if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    _err "-n option requires a value."
                fi
                OUT_LINE_NUMBER=$2
                shift 2
                ;;
            -- | -) # after this all args include '-xx', will treat arg value
                shift
                ARG_VALUES+=( "$@" )
                break
                ;;
            --*) # for true or false flags, no argument
                if [[ "$1" =~ 'no-symbol' ]]; then
                    NO_SYMBOL=true
                fi
                shift
                ;;
            *)
                ARG_VALUES+=("$1")
                shift
                ;;
        esac
    done
}

# -------------------------------------------------------------
# Main Routine
# -------------------------------------------------------------
_analyse_args_and_options $@ && {
    _verbose
    _main
}
exit 0
